export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { createRoute } from "@/lib/api-middleware";
import type { JobStatus, WorkMode } from "@prisma/client";
import { autoGenerateAndPersistJobSkills } from "@/lib/job-skill-generation";
import { logJobPageAudit } from "@/lib/job-page-audit";

export const PATCH = createRoute(
  {
    requireAuth: true,
    requireOrg: true,
    permission: "jobs:write",
    rateLimit: { type: "api" },
  },
  async (req: NextRequest, { params, orgId, userId }) => {
    const { jobId } = params as { orgId: string; jobId: string };
    const body = await req.json().catch(() => ({}));

    const title = String(body?.title ?? "").trim();
    const description =
      body?.description === null || body?.description === undefined
        ? null
        : String(body.description).trim() || null;
    const location =
      body?.location === null || body?.location === undefined
        ? null
        : String(body.location).trim() || null;
    const status =
      body?.status === null || body?.status === undefined
        ? null
        : String(body.status).trim() || null;
    const workModeRaw =
      body?.workMode === null || body?.workMode === undefined
        ? null
        : String(body.workMode).trim().toUpperCase();
    const normalizedStatus: JobStatus =
      status === "CLOSED" ? "CLOSED" : "OPEN";
    const normalizedWorkMode: WorkMode | null =
      workModeRaw === "REMOTE" ||
      workModeRaw === "ONSITE" ||
      workModeRaw === "HYBRID" ||
      workModeRaw === "OTHER"
        ? (workModeRaw as WorkMode)
        : null;
    const workModeOtherRaw =
      body?.workModeOther === null || body?.workModeOther === undefined
        ? null
        : String(body.workModeOther).trim();
    const workModeOther =
      normalizedWorkMode === "OTHER" ? workModeOtherRaw || "Other" : null;

    if (!title) {
      return NextResponse.json({ error: "Title is required" }, { status: 400 });
    }

    const job = await prisma.job.findFirst({
      where: { id: jobId, orgId },
      select: {
        id: true,
        title: true,
        description: true,
        location: true,
        status: true,
        workMode: true,
        workModeOther: true,
      },
    });

    if (!job) {
      return NextResponse.json({ error: "Job not found" }, { status: 404 });
    }

    const updated = await prisma.job.update({
      where: { id: jobId },
      data: {
        title,
        description,
        location,
        status: normalizedStatus,
        workMode: normalizedWorkMode,
        workModeOther,
      },
      select: {
        id: true,
        title: true,
        description: true,
        location: true,
        status: true,
        workMode: true,
        workModeOther: true,
        createdAt: true,
      },
    });

    let autoGeneratedSkills = 0;
    if (updated.description) {
      const generated = await autoGenerateAndPersistJobSkills({
        orgId: orgId!,
        jobId,
        description: updated.description,
        onlyWhenEmpty: true,
        source: "AUTO_UPDATE",
        triggeredBy: userId,
      });
      autoGeneratedSkills = generated.generated;
    }

    const changedFields: string[] = [];
    if (job.title !== updated.title) changedFields.push("title");
    if ((job.description ?? null) !== (updated.description ?? null)) changedFields.push("description");
    if ((job.location ?? null) !== (updated.location ?? null)) changedFields.push("location");
    if (job.status !== updated.status) changedFields.push("status");
    if ((job.workMode ?? null) !== (updated.workMode ?? null)) changedFields.push("workMode");
    if ((job.workModeOther ?? null) !== (updated.workModeOther ?? null)) changedFields.push("workModeOther");

    await logJobPageAudit({
      orgId: orgId!,
      jobId,
      actorId: userId,
      action: "JOB_DETAILS_UPDATED",
      summary: "Updated job details",
      metadata: {
        changedFields,
      },
    });

    if (autoGeneratedSkills > 0) {
      await logJobPageAudit({
        orgId: orgId!,
        jobId,
        actorId: userId,
        action: "JOB_SKILLS_GENERATED",
        summary: "Auto-generated skills from description",
        metadata: {
          source: "AUTO_UPDATE",
          generatedCount: autoGeneratedSkills,
        },
      });
    }

    return NextResponse.json({ ok: true, job: updated, autoGeneratedSkills });
  }
);

export const DELETE = createRoute(
  {
    requireAuth: true,
    requireOrg: true,
    permission: "jobs:delete",
    rateLimit: { type: "api" },
  },
  async (_req, { params, orgId, userId }) => {
    const { jobId } = params as { orgId: string; jobId: string };

    const job = await prisma.job.findFirst({
      where: { id: jobId, orgId },
      select: { id: true, title: true },
    });

    if (!job) {
      return NextResponse.json({ error: "Job not found" }, { status: 404 });
    }

    await logJobPageAudit({
      orgId: orgId!,
      jobId,
      actorId: userId,
      action: "JOB_DELETED",
      summary: "Deleted job",
      metadata: {
        title: job.title,
      },
    });

    await prisma.job.delete({
      where: { id: jobId },
    });

    return NextResponse.json({ ok: true, deletedJobId: jobId });
  }
);
