export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { createRoute } from "@/lib/api-middleware";
import type { JobStatus, WorkMode } from "@prisma/client";
import { autoGenerateAndPersistJobSkills } from "@/lib/job-skill-generation";
import { logJobPageAudit } from "@/lib/job-page-audit";

export const PATCH = createRoute(
  {
    requireAuth: true,
    requireOrg: true,
    permission: "jobs:write",
    rateLimit: { type: "api" },
  },
  async (req: NextRequest, { params, orgId, userId }) => {
    const { jobId } = params as { orgId: string; jobId: string };
    const body = await req.json().catch(() => ({}));

    const title = String(body?.title ?? "").trim();
    const company = body?.company == null ? null : String(body.company).trim() || null;
    const department = body?.department == null ? null : String(body.department).trim() || null;
    const description =
      body?.description === null || body?.description === undefined
        ? null
        : String(body.description).trim() || null;
    const location =
      body?.location === null || body?.location === undefined
        ? null
        : String(body.location).trim() || null;
    const status =
      body?.status === null || body?.status === undefined
        ? null
        : String(body.status).trim() || null;
    const workModeRaw =
      body?.workMode === null || body?.workMode === undefined
        ? null
        : String(body.workMode).trim().toUpperCase();
    const normalizedStatus: JobStatus =
      status === "CLOSED" ? "CLOSED" : "OPEN";
    const normalizedWorkMode: WorkMode | null =
      workModeRaw === "REMOTE" ||
      workModeRaw === "ONSITE" ||
      workModeRaw === "HYBRID" ||
      workModeRaw === "OTHER"
        ? (workModeRaw as WorkMode)
        : null;
    const workModeOtherRaw =
      body?.workModeOther === null || body?.workModeOther === undefined
        ? null
        : String(body.workModeOther).trim();
    const workModeOther =
      normalizedWorkMode === "OTHER" ? workModeOtherRaw || "Other" : null;

    const yearsRaw = body?.requiredYearsOfExperience;
    const requiredYearsOfExperience =
      yearsRaw === null || yearsRaw === undefined || yearsRaw === ""
        ? null
        : Math.max(0, Math.trunc(Number(yearsRaw)));

    const salaryMin = body?.salaryMin == null ? null : Math.max(0, Math.trunc(Number(body.salaryMin))) || null;
    const salaryMax = body?.salaryMax == null ? null : Math.max(0, Math.trunc(Number(body.salaryMax))) || null;
    const salaryCurrency = body?.salaryCurrency == null ? null : String(body.salaryCurrency).trim().toUpperCase() || null;
    const closingDate = body?.closingDate == null ? null : (() => { const d = new Date(body.closingDate); return isNaN(d.getTime()) ? null : d; })();
    const openingsCount = body?.openingsCount == null ? null : Math.max(1, Math.trunc(Number(body.openingsCount))) || null;

    if (!title) {
      return NextResponse.json({ error: "Title is required" }, { status: 400 });
    }

    const job = await prisma.job.findFirst({
      where: { id: jobId, orgId },
      select: {
        id: true,
        title: true,
        company: true,
        department: true,
        description: true,
        location: true,
        status: true,
        workMode: true,
        workModeOther: true,
        requiredYearsOfExperience: true,
        salaryMin: true,
        salaryMax: true,
        salaryCurrency: true,
        closingDate: true,
        openingsCount: true,
      },
    });

    if (!job) {
      return NextResponse.json({ error: "Job not found" }, { status: 404 });
    }

    const updated = await prisma.job.update({
      where: { id: jobId },
      data: {
        title,
        company,
        department,
        description,
        location,
        status: normalizedStatus,
        workMode: normalizedWorkMode,
        workModeOther,
        requiredYearsOfExperience,
        salaryMin,
        salaryMax,
        salaryCurrency,
        closingDate,
        openingsCount,
      },
      select: {
        id: true,
        title: true,
        company: true,
        department: true,
        description: true,
        location: true,
        status: true,
        workMode: true,
        workModeOther: true,
        requiredYearsOfExperience: true,
        salaryMin: true,
        salaryMax: true,
        salaryCurrency: true,
        closingDate: true,
        openingsCount: true,
        createdAt: true,
      },
    });

    let autoGeneratedSkills = 0;
    if (updated.description) {
      const generated = await autoGenerateAndPersistJobSkills({
        orgId: orgId!,
        jobId,
        description: updated.description,
        onlyWhenEmpty: true,
        source: "AUTO_UPDATE",
        triggeredBy: userId,
      });
      autoGeneratedSkills = generated.generated;
    }

    const changedFields: string[] = [];
    if (job.title !== updated.title) changedFields.push("title");
    if ((job.company ?? null) !== (updated.company ?? null)) changedFields.push("company");
    if ((job.department ?? null) !== (updated.department ?? null)) changedFields.push("department");
    if ((job.description ?? null) !== (updated.description ?? null)) changedFields.push("description");
    if ((job.location ?? null) !== (updated.location ?? null)) changedFields.push("location");
    if (job.status !== updated.status) changedFields.push("status");
    if ((job.workMode ?? null) !== (updated.workMode ?? null)) changedFields.push("workMode");
    if ((job.workModeOther ?? null) !== (updated.workModeOther ?? null)) changedFields.push("workModeOther");
    if ((job.requiredYearsOfExperience ?? null) !== (updated.requiredYearsOfExperience ?? null)) changedFields.push("requiredYearsOfExperience");
    if ((job.salaryMin ?? null) !== (updated.salaryMin ?? null)) changedFields.push("salaryMin");
    if ((job.salaryMax ?? null) !== (updated.salaryMax ?? null)) changedFields.push("salaryMax");
    if ((job.salaryCurrency ?? null) !== (updated.salaryCurrency ?? null)) changedFields.push("salaryCurrency");
    if ((job.closingDate?.getTime() ?? null) !== (updated.closingDate?.getTime() ?? null)) changedFields.push("closingDate");
    if ((job.openingsCount ?? null) !== (updated.openingsCount ?? null)) changedFields.push("openingsCount");

    await logJobPageAudit({
      orgId: orgId!,
      jobId,
      actorId: userId,
      action: "JOB_DETAILS_UPDATED",
      summary: "Updated job details",
      metadata: {
        changedFields,
      },
    });

    if (autoGeneratedSkills > 0) {
      await logJobPageAudit({
        orgId: orgId!,
        jobId,
        actorId: userId,
        action: "JOB_SKILLS_GENERATED",
        summary: "Auto-generated skills from description",
        metadata: {
          source: "AUTO_UPDATE",
          generatedCount: autoGeneratedSkills,
        },
      });
    }

    return NextResponse.json({ ok: true, job: updated, autoGeneratedSkills });
  }
);

export const DELETE = createRoute(
  {
    requireAuth: true,
    requireOrg: true,
    permission: "jobs:delete",
    rateLimit: { type: "api" },
  },
  async (_req, { params, orgId, userId }) => {
    const { jobId } = params as { orgId: string; jobId: string };

    const job = await prisma.job.findFirst({
      where: { id: jobId, orgId },
      select: { id: true, title: true },
    });

    if (!job) {
      return NextResponse.json({ error: "Job not found" }, { status: 404 });
    }

    await logJobPageAudit({
      orgId: orgId!,
      jobId,
      actorId: userId,
      action: "JOB_DELETED",
      summary: "Deleted job",
      metadata: {
        title: job.title,
      },
    });

    await prisma.job.delete({
      where: { id: jobId },
    });

    return NextResponse.json({ ok: true, deletedJobId: jobId });
  }
);
